#!/bin/sh
echo"enter the firt number:"
read first
echo"enter the second number:"
read second
temp=$first
first=$second
second=$temp
echo "after swapping:"
echo   "first  number=$first, second  number=$second"

